// City-specific metadata for unique content generation
// This provides REAL, unique data for each city - not just template swaps

export type ClimateType = 'coastal' | 'inland' | 'highland' | 'island' | 'urban';
export type PriceTier = 'premium' | 'standard' | 'budget';
export type AreaType = 'urban' | 'suburban' | 'rural';
export type PopulationTier = 'major' | 'medium' | 'small';

export interface LocalCouncil {
  name: string;
  shortName: string;
  website: string;
  dogLicenseFee: string;
  spayedFee: string;
}

export interface DVSOffice {
  name: string;
  address: string;
  phone: string;
  email: string;
}

export interface CityMetadata {
  slug: string;
  population: number;
  populationTier: PopulationTier;
  areaType: AreaType;
  climate: ClimateType;
  
  // City-specific risks (different for each climate/type)
  petRisks: string[];
  
  // Real local landmarks for testimonials
  landmarks: string[];
  
  // Pricing tier (based on city economics)
  vetPriceTier: PriceTier;
  avgEmergencyVetCost: { min: number; max: number };
  avgConsultationCost: { min: number; max: number };
  avgGroomingCost: { min: number; max: number };
  
  // Content variation selectors (hash-based pools)
  testimonialPoolIndex: number;
  scenarioPoolIndex: number;
  vetAdviceIndex: number;
  
  // Hub reference for smaller cities
  nearestMajorCity?: string;
  distanceToHub?: string;
  
  // Coordinates for schema
  coordinates: { lat: string; lng: string };
}

// State-level DVS offices (13 unique offices)
export const dvsOffices: Record<string, DVSOffice> = {
  'W.P. Kuala Lumpur': {
    name: 'Jabatan Perkhidmatan Veterinar Wilayah Persekutuan',
    address: 'Aras 3, Bangunan Podium, Lot 4G3, Presint 4, 62574 Putrajaya',
    phone: '+60 3-8870 2000',
    email: 'dvswp@dvs.gov.my'
  },
  'Selangor': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Selangor',
    address: 'Tingkat 4, Bangunan Sultan Salahuddin Abdul Aziz Shah, 40000 Shah Alam',
    phone: '+60 3-5510 2400',
    email: 'jphselangor@dvs.gov.my'
  },
  'Johor': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Johor',
    address: 'Aras 4, Bangunan Sultan Ibrahim, Bukit Timbalan, 80000 Johor Bahru',
    phone: '+60 7-223 6100',
    email: 'jpvjohor@dvs.gov.my'
  },
  'Penang': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Pulau Pinang',
    address: 'Tingkat 36, Komtar, 10000 George Town',
    phone: '+60 4-650 5500',
    email: 'jpvpulpinang@dvs.gov.my'
  },
  'Perak': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Perak',
    address: 'Aras 2, Bangunan Perak Darul Ridzuan, 30000 Ipoh',
    phone: '+60 5-253 1957',
    email: 'jpvperak@dvs.gov.my'
  },
  'Sarawak': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Sarawak',
    address: 'Tingkat 8, Wisma Sumber Alam, Petra Jaya, 93050 Kuching',
    phone: '+60 82-441 971',
    email: 'jpvsarawak@dvs.gov.my'
  },
  'Sabah': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Sabah',
    address: 'Tingkat 2, Blok A, Wisma Pertanian, 88624 Kota Kinabalu',
    phone: '+60 88-253 199',
    email: 'jpvsabah@dvs.gov.my'
  },
  'Melaka': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Melaka',
    address: 'Aras 4, Wisma Negeri, 75450 Ayer Keroh',
    phone: '+60 6-232 7800',
    email: 'jpvmelaka@dvs.gov.my'
  },
  'Kedah': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Kedah',
    address: 'Tingkat 16, Wisma Negeri, 05503 Alor Setar',
    phone: '+60 4-774 8000',
    email: 'jpvkedah@dvs.gov.my'
  },
  'Pahang': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Pahang',
    address: 'Tingkat 4, Kompleks Tun Razak, 25200 Kuantan',
    phone: '+60 9-571 1500',
    email: 'jpvpahang@dvs.gov.my'
  },
  'Kelantan': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Kelantan',
    address: 'Tingkat 8, Wisma Persekutuan, 15200 Kota Bharu',
    phone: '+60 9-748 3833',
    email: 'jpvkelantan@dvs.gov.my'
  },
  'Terengganu': {
    name: 'Jabatan Perkhidmatan Veterinar Negeri Terengganu',
    address: 'Aras 5, Wisma Negeri, 20200 Kuala Terengganu',
    phone: '+60 9-622 1422',
    email: 'jpvterengganu@dvs.gov.my'
  }
};

// Local council contacts (unique for each major city)
export const localCouncils: Record<string, LocalCouncil> = {
  'kuala-lumpur': {
    name: 'Dewan Bandaraya Kuala Lumpur',
    shortName: 'DBKL',
    website: 'https://www.dbkl.gov.my',
    dogLicenseFee: 'RM50/year',
    spayedFee: 'RM10/year'
  },
  'petaling-jaya': {
    name: 'Majlis Bandaraya Petaling Jaya',
    shortName: 'MBPJ',
    website: 'https://www.mbpj.gov.my',
    dogLicenseFee: 'RM50/year',
    spayedFee: 'RM10/year'
  },
  'shah-alam': {
    name: 'Majlis Bandaraya Shah Alam',
    shortName: 'MBSA',
    website: 'https://www.mbsa.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'subang-jaya': {
    name: 'Majlis Bandaraya Subang Jaya',
    shortName: 'MBSJ',
    website: 'https://www.mbsj.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'klang': {
    name: 'Majlis Perbandaran Klang',
    shortName: 'MPK',
    website: 'https://www.mpklang.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'johor-bahru': {
    name: 'Majlis Bandaraya Johor Bahru',
    shortName: 'MBJB',
    website: 'https://www.mbjb.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'iskandar-puteri': {
    name: 'Majlis Bandaraya Iskandar Puteri',
    shortName: 'MBIP',
    website: 'https://www.mbip.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'george-town': {
    name: 'Majlis Bandaraya Pulau Pinang',
    shortName: 'MBPP',
    website: 'https://www.mbpp.gov.my',
    dogLicenseFee: 'RM24/year',
    spayedFee: 'RM12/year'
  },
  'butterworth': {
    name: 'Majlis Bandaraya Seberang Perai',
    shortName: 'MBSP',
    website: 'https://www.mbsp.gov.my',
    dogLicenseFee: 'RM24/year',
    spayedFee: 'RM12/year'
  },
  'ipoh': {
    name: 'Majlis Bandaraya Ipoh',
    shortName: 'MBI',
    website: 'https://www.mbi.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'kuching': {
    name: 'Dewan Bandaraya Kuching Utara',
    shortName: 'DBKU',
    website: 'https://www.dbku.sarawak.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'kota-kinabalu': {
    name: 'Dewan Bandaraya Kota Kinabalu',
    shortName: 'DBKK',
    website: 'https://www.dbkk.sabah.gov.my',
    dogLicenseFee: 'RM25/year',
    spayedFee: 'RM10/year'
  },
  'melaka-city': {
    name: 'Majlis Bandaraya Melaka Bersejarah',
    shortName: 'MBMB',
    website: 'https://www.mbmb.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'alor-setar': {
    name: 'Majlis Bandaraya Alor Setar',
    shortName: 'MBAS',
    website: 'https://www.mbas.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'kuantan': {
    name: 'Majlis Bandaraya Kuantan',
    shortName: 'MBK',
    website: 'https://www.mbkuantan.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'kota-bharu': {
    name: 'Majlis Bandaraya Kota Bharu',
    shortName: 'MPKB',
    website: 'https://www.mpkb.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'kuala-terengganu': {
    name: 'Majlis Bandaraya Kuala Terengganu',
    shortName: 'MBKT',
    website: 'https://www.mbkt.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'puchong': {
    name: 'Majlis Bandaraya Subang Jaya',
    shortName: 'MBSJ',
    website: 'https://www.mbsj.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'kajang': {
    name: 'Majlis Perbandaran Kajang',
    shortName: 'MPKj',
    website: 'https://www.mpkj.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'ampang': {
    name: 'Majlis Perbandaran Ampang Jaya',
    shortName: 'MPAJ',
    website: 'https://www.mpaj.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'seri-kembangan': {
    name: 'Majlis Perbandaran Subang Jaya',
    shortName: 'MPSJ',
    website: 'https://www.mpsj.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'rawang': {
    name: 'Majlis Perbandaran Selayang',
    shortName: 'MPS',
    website: 'https://www.mps.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  },
  'cyberjaya': {
    name: 'Majlis Perbandaran Sepang',
    shortName: 'MPSepang',
    website: 'https://www.mpsepang.gov.my',
    dogLicenseFee: 'RM30/year',
    spayedFee: 'RM10/year'
  },
  'putrajaya': {
    name: 'Perbadanan Putrajaya',
    shortName: 'PPj',
    website: 'https://www.ppj.gov.my',
    dogLicenseFee: 'RM50/year',
    spayedFee: 'RM15/year'
  },
  'kulai': {
    name: 'Majlis Perbandaran Kulai',
    shortName: 'MPKu',
    website: 'https://www.mpkulai.gov.my',
    dogLicenseFee: 'RM25/year',
    spayedFee: 'RM10/year'
  }
};

// City-specific metadata with REAL unique data
export const cityMetadata: Record<string, CityMetadata> = {
  // ========== KUALA LUMPUR HUB ==========
  'kuala-lumpur': {
    slug: 'kuala-lumpur',
    population: 1982000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['high traffic accidents', 'apartment balcony falls', 'heatstroke from concrete', 'air pollution effects'],
    landmarks: ['KLCC', 'Bukit Bintang', 'Mid Valley', 'Bangsar', 'Publika'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 300, max: 800 },
    avgConsultationCost: { min: 80, max: 200 },
    avgGroomingCost: { min: 60, max: 180 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    coordinates: { lat: '3.1390', lng: '101.6869' }
  },
  'bangsar': {
    slug: 'bangsar',
    population: 45000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['off-leash park injuries', 'restaurant food scraps poisoning', 'luxury condo falls'],
    landmarks: ['Bangsar Village', 'Bangsar South', 'Lucky Garden', 'Telawi Street'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 350, max: 900 },
    avgConsultationCost: { min: 100, max: 250 },
    avgGroomingCost: { min: 80, max: 200 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.1296', lng: '101.6720' }
  },
  'cheras': {
    slug: 'cheras',
    population: 832000,
    populationTier: 'major',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['highway traffic accidents', 'stray dog encounters', 'industrial area toxins'],
    landmarks: ['Sunway Velocity', 'Cheras Leisure Mall', 'Taman Connaught', 'IKEA Cheras'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 150 },
    avgGroomingCost: { min: 40, max: 120 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.0613', lng: '101.7644' }
  },
  'kepong': {
    slug: 'kepong',
    population: 235000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['wet market food poisoning', 'motorcycle accidents', 'monsoon drain dangers'],
    landmarks: ['Kepong Baru', 'Metro Prima', 'Desa Park City', 'Menjalara'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 120 },
    avgGroomingCost: { min: 35, max: 100 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '20 minutes',
    coordinates: { lat: '3.2107', lng: '101.6348' }
  },
  'setapak': {
    slug: 'setapak',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['university area strays', 'old building hazards', 'flash floods'],
    landmarks: ['Setapak Central', 'Wangsa Walk', 'TARUMT area', 'Danau Kota'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 400 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.1897', lng: '101.7162' }
  },
  'mont-kiara': {
    slug: 'mont-kiara',
    population: 68000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['high-rise condo falls', 'exotic pet smuggling', 'imported food allergies'],
    landmarks: ['1 Mont Kiara', 'Solaris Mont Kiara', 'Arcoris', 'Plaza Mont Kiara'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 400, max: 1000 },
    avgConsultationCost: { min: 120, max: 300 },
    avgGroomingCost: { min: 100, max: 250 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.1717', lng: '101.6510' }
  },
  'brickfields': {
    slug: 'brickfields',
    population: 32000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['train station crowds', 'busy traffic', 'festival firecrackers'],
    landmarks: ['KL Sentral', 'Little India', 'Vivekananda Ashram', 'Brickfields Walk'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 550 },
    avgConsultationCost: { min: 70, max: 160 },
    avgGroomingCost: { min: 50, max: 130 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.1257', lng: '101.6869' }
  },
  'klcc': {
    slug: 'klcc',
    population: 25000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['luxury condo restrictions', 'extreme heat reflection', 'limited green space'],
    landmarks: ['Petronas Twin Towers', 'KLCC Park', 'Suria KLCC', 'Ampang Park'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 400, max: 1000 },
    avgConsultationCost: { min: 120, max: 280 },
    avgGroomingCost: { min: 90, max: 220 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '0 minutes',
    coordinates: { lat: '3.1579', lng: '101.7123' }
  },
  'wangsa-maju': {
    slug: 'wangsa-maju',
    population: 145000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['busy LRT areas', 'playground injuries', 'apartment complex strays'],
    landmarks: ['AEON Alpha Angle', 'Wangsa Walk Mall', 'Section 2', 'Wangsa Maju LRT'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.2052', lng: '101.7329' }
  },
  'taman-melawati': {
    slug: 'taman-melawati',
    population: 87000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['zoo animal escapes nearby', 'forest edge wildlife', 'jungle trails hazards'],
    landmarks: ['Zoo Negara', 'Melawati Mall', 'Taman Melawati Park', 'Wangsa Melawati'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '20 minutes',
    coordinates: { lat: '3.2185', lng: '101.7523' }
  },
  
  // ========== PETALING JAYA HUB ==========
  'petaling-jaya': {
    slug: 'petaling-jaya',
    population: 638516,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['Federal Highway accidents', 'high-rise falls', 'construction site hazards', 'stray dog packs'],
    landmarks: ['1 Utama', 'The Curve', 'Jaya One', 'SS2', 'Damansara Uptown'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 280, max: 700 },
    avgConsultationCost: { min: 80, max: 180 },
    avgGroomingCost: { min: 60, max: 160 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 1,
    coordinates: { lat: '3.1073', lng: '101.6067' }
  },
  'bandar-utama': {
    slug: 'bandar-utama',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['shopping mall parking lot dangers', 'gated community escapees', 'pool drowning'],
    landmarks: ['1 Utama Shopping Centre', 'TTDI', 'Centrepoint Bandar Utama', 'BU11'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 300, max: 750 },
    avgConsultationCost: { min: 90, max: 200 },
    avgGroomingCost: { min: 70, max: 170 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.1439', lng: '101.6041' }
  },
  'kota-damansara': {
    slug: 'kota-damansara',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['MRT construction noise stress', 'new development strays', 'playground injuries'],
    landmarks: ['The Strand', 'Encorp Strand', 'Sunway Giza', 'Dataran Sunway'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 45, max: 120 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.1505', lng: '101.5832' }
  },
  'ara-damansara': {
    slug: 'ara-damansara',
    population: 67000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['condo elevator incidents', 'jogging path accidents', 'imported pet food issues'],
    landmarks: ['Citta Mall', 'Oasis Square', 'Evolve Concept Mall', 'Ara Damansara LRT'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 280, max: 680 },
    avgConsultationCost: { min: 80, max: 180 },
    avgGroomingCost: { min: 60, max: 150 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '12 minutes',
    coordinates: { lat: '3.1139', lng: '101.5762' }
  },
  'ss2': {
    slug: 'ss2',
    population: 45000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['pasar malam crowds', 'old shophouse hazards', 'street food poisoning'],
    landmarks: ['SS2 Pasar Malam', 'Murni SS2', 'SS2 Park', 'Jalan SS2/72'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.1187', lng: '101.6219' }
  },
  'kelana-jaya': {
    slug: 'kelana-jaya',
    population: 112000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['LRT station crowds', 'lake park drowning', 'condo complex strays'],
    landmarks: ['Paradigm Mall', 'Kelana Jaya LRT', 'Kelana Jaya Lake', 'SS7'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 520 },
    avgConsultationCost: { min: 60, max: 150 },
    avgGroomingCost: { min: 50, max: 120 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '8 minutes',
    coordinates: { lat: '3.1009', lng: '101.6102' }
  },
  'tropicana': {
    slug: 'tropicana',
    population: 52000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['golf course pesticides', 'luxury pet obesity', 'imported breed health issues'],
    landmarks: ['Tropicana Golf', 'Tropicana City Mall', 'Tropicana Gardens', 'Casa Tropicana'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 350, max: 850 },
    avgConsultationCost: { min: 100, max: 220 },
    avgGroomingCost: { min: 80, max: 180 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.1358', lng: '101.5947' }
  },
  'taman-megah': {
    slug: 'taman-megah',
    population: 38000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['old housing estate strays', 'hawker center food scraps', 'drain hazards'],
    landmarks: ['Giant Taman Megah', 'SS24/2', 'Taman Megah Park', 'Sea Park nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 400 },
    avgConsultationCost: { min: 45, max: 100 },
    avgGroomingCost: { min: 35, max: 80 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Petaling Jaya',
    distanceToHub: '8 minutes',
    coordinates: { lat: '3.1048', lng: '101.6289' }
  },
  
  // ========== SHAH ALAM HUB ==========
  'shah-alam': {
    slug: 'shah-alam',
    population: 650000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['industrial area toxins', 'stadium event crowds', 'highway accidents', 'flash floods'],
    landmarks: ['i-City', 'Shah Alam Stadium', 'Blue Mosque', 'SACC Mall', 'Setia City Mall'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    coordinates: { lat: '3.0733', lng: '101.5185' }
  },
  'setia-alam': {
    slug: 'setia-alam',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['new township strays', 'construction sites', 'limited vet access'],
    landmarks: ['Setia City Mall', 'Central Park', 'Top Glove Tower', 'Setia Alam Pasar Malam'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 120 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Shah Alam',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.1078', lng: '101.4485' }
  },
  'bukit-jelutong': {
    slug: 'bukit-jelutong',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['gated community escapees', 'golf course chemicals', 'limited 24h care'],
    landmarks: ['Bukit Jelutong Golf', 'AEON Bukit Jelutong', 'Jelutong Heights', 'U10 Commercial'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 250, max: 600 },
    avgConsultationCost: { min: 70, max: 160 },
    avgGroomingCost: { min: 55, max: 140 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Shah Alam',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.0989', lng: '101.5358' }
  },
  'seksyen-7': {
    slug: 'seksyen-7',
    population: 62000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['commercial area traffic', 'stadium event noise', 'pasar hazards'],
    landmarks: ['Stadium Shah Alam', 'Section 7 Commercial', 'Giant Section 7', 'Section 7 Mosque'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Shah Alam',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.0847', lng: '101.5189' }
  },
  'seksyen-13': {
    slug: 'seksyen-13',
    population: 55000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['industrial area chemicals', 'heavy traffic', 'factory strays'],
    landmarks: ['SACC Mall', 'Section 13 Industrial', 'Wet World', 'Komtar JBCC nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 350 },
    avgConsultationCost: { min: 40, max: 90 },
    avgGroomingCost: { min: 30, max: 75 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Shah Alam',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.0625', lng: '101.5311' }
  },
  
  // ========== SUBANG JAYA HUB ==========
  'subang-jaya': {
    slug: 'subang-jaya',
    population: 708296,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['university area strays', 'busy highway traffic', 'flooding during monsoon', 'airport noise stress'],
    landmarks: ['Sunway Pyramid', 'Empire Shopping Gallery', 'Subang Parade', 'SS15', 'Taylor\'s University'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 150 },
    avgGroomingCost: { min: 45, max: 120 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 3,
    coordinates: { lat: '3.0565', lng: '101.5851' }
  },
  'usj': {
    slug: 'usj',
    population: 320000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['large township strays', 'drainage hazards', 'park injuries'],
    landmarks: ['Main Place Mall', 'Summit USJ', 'USJ 1 Taipan', 'USJ Park'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Subang Jaya',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.0467', lng: '101.5937' }
  },
  'taipan': {
    slug: 'taipan',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['commercial area traffic', 'restaurant scraps', 'parking lot hazards'],
    landmarks: ['Taipan Business Centre', 'USJ 10', 'Taipan Lake', 'Subang Bestari nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Subang Jaya',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.0389', lng: '101.5896' }
  },
  'putra-heights': {
    slug: 'putra-heights',
    population: 98000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['new development hazards', 'limited vet options', 'stray animals'],
    landmarks: ['Putra Heights LRT', 'Saujana Putra', 'Putra Heights Park', 'South City Plaza nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 120 },
    avgGroomingCost: { min: 40, max: 95 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Subang Jaya',
    distanceToHub: '15 minutes',
    coordinates: { lat: '2.9864', lng: '101.5759' }
  },
  
  // ========== PUCHONG HUB ==========
  'puchong': {
    slug: 'puchong',
    population: 520000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['LDP highway accidents', 'IOI Mall crowd stress', 'high-rise condo falls', 'construction site hazards'],
    landmarks: ['IOI Mall', 'Setia Walk', 'IOI City Mall', 'Bandar Puteri', 'LDP Highway'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 520 },
    avgConsultationCost: { min: 60, max: 150 },
    avgGroomingCost: { min: 45, max: 120 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 2,
    coordinates: { lat: '3.0322', lng: '101.6173' }
  },
  'bandar-puteri': {
    slug: 'bandar-puteri',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['gated community escapees', 'landscaped garden pesticides', 'pool accidents'],
    landmarks: ['Bandar Puteri Commercial', 'Puteri Mart', 'IOI Mall nearby', 'Setia Walk nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 145 },
    avgGroomingCost: { min: 48, max: 115 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Puchong',
    distanceToHub: '5 minutes',
    coordinates: { lat: '3.0245', lng: '101.6198' }
  },
  'bukit-puchong': {
    slug: 'bukit-puchong',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['semi-rural wildlife', 'limited evening vet access', 'drainage hazards'],
    landmarks: ['BP Walk', 'Bukit Puchong Recreational Park', 'Pusat Perniagaan BP', 'Puchong South nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 160, max: 400 },
    avgConsultationCost: { min: 45, max: 110 },
    avgGroomingCost: { min: 35, max: 85 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Puchong',
    distanceToHub: '10 minutes',
    coordinates: { lat: '2.9987', lng: '101.6356' }
  },

  // ========== KAJANG HUB ==========
  'kajang': {
    slug: 'kajang',
    population: 450000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['MRT construction zones', 'satay street food hazards', 'semi-urban wildlife', 'flooding in low areas'],
    landmarks: ['Stadium Kajang', 'Metro Point', 'Kajang MRT', 'Bandar Baru Bangi', 'Sungai Chua'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 1,
    coordinates: { lat: '2.9927', lng: '101.7909' }
  },
  'bandar-baru-bangi': {
    slug: 'bandar-baru-bangi',
    population: 180000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['university strays', 'forest edge wildlife', 'new development sites'],
    landmarks: ['UKM Campus', 'Bangi Gateway', 'EkoCheras nearby', 'GIANT Bangi'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 170, max: 430 },
    avgConsultationCost: { min: 48, max: 120 },
    avgGroomingCost: { min: 38, max: 95 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kajang',
    distanceToHub: '10 minutes',
    coordinates: { lat: '2.9394', lng: '101.7782' }
  },
  'sungai-chua': {
    slug: 'sungai-chua',
    population: 65000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['old town traffic', 'market area strays', 'monsoon drain flooding'],
    landmarks: ['Kajang Wet Market', 'Sungai Chua Town', 'Stadium Kajang nearby', 'Metro Point nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 32, max: 80 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kajang',
    distanceToHub: '5 minutes',
    coordinates: { lat: '2.9856', lng: '101.7821' }
  },
  
  // ========== SERI KEMBANGAN HUB ==========
  'seri-kembangan': {
    slug: 'seri-kembangan',
    population: 280000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['MRT station crowds', 'industrial area toxins', 'busy highway traffic', 'university strays'],
    landmarks: ['The Mines', 'Serdang Perdana', 'UPM Campus', 'Seri Kembangan MRT', 'Giant Seri Kembangan'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 460 },
    avgConsultationCost: { min: 55, max: 135 },
    avgGroomingCost: { min: 42, max: 105 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '25 minutes',
    coordinates: { lat: '3.0271', lng: '101.7173' }
  },
  'serdang': {
    slug: 'serdang',
    population: 145000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['UPM campus wildlife', 'agricultural research animals', 'semi-rural hazards'],
    landmarks: ['UPM Serdang', 'Serdang Raya', 'MARDI', 'MyTown nearby', 'The Mines nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 160, max: 400 },
    avgConsultationCost: { min: 45, max: 110 },
    avgGroomingCost: { min: 35, max: 88 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Seri Kembangan',
    distanceToHub: '8 minutes',
    coordinates: { lat: '3.0112', lng: '101.7067' }
  },

  // ========== AMPANG HUB ==========
  'ampang': {
    slug: 'ampang',
    population: 320000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['hillside landslides', 'forest edge wildlife encounters', 'busy MRR2 traffic', 'flash floods'],
    landmarks: ['Great Eastern Mall', 'Ampang Point', 'Ampang Hilir', 'Zoo Negara nearby', 'Ampang LRT'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 145 },
    avgGroomingCost: { min: 48, max: 120 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.1478', lng: '101.7608' }
  },
  'pandan-indah': {
    slug: 'pandan-indah',
    population: 95000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['LRT station traffic', 'old housing estate strays', 'drainage flooding'],
    landmarks: ['Pandan Indah LRT', 'Pandan Kapital', 'Pandan Perdana', 'Ampang Point nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 160, max: 400 },
    avgConsultationCost: { min: 48, max: 115 },
    avgGroomingCost: { min: 38, max: 92 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Ampang',
    distanceToHub: '8 minutes',
    coordinates: { lat: '3.1334', lng: '101.7489' }
  },
  
  // ========== RAWANG HUB ==========
  'rawang': {
    slug: 'rawang',
    population: 200000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['semi-rural wildlife', 'tin mine lake hazards', 'agricultural pesticides', 'long distance to specialist vets'],
    landmarks: ['Rawang Wet Market', 'Anggun City', 'Kota Emerald', 'Templer Park nearby', 'Selayang nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 42, max: 105 },
    avgGroomingCost: { min: 32, max: 80 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kuala Lumpur',
    distanceToHub: '35 minutes',
    coordinates: { lat: '3.3213', lng: '101.5765' }
  },
  'bandar-country-homes': {
    slug: 'bandar-country-homes',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['gated community escapees', 'rural wildlife encounters', 'limited night vet access'],
    landmarks: ['Country Homes Commercial', 'Rawang Town nearby', 'Templer Park nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 350 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 30, max: 72 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Rawang',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.3456', lng: '101.5623' }
  },
  
  // ========== CYBERJAYA HUB ==========
  'cyberjaya': {
    slug: 'cyberjaya',
    population: 120000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'urban',
    petRisks: ['tech campus isolation', 'limited pet services', 'hot pavement burns', 'long commute for emergencies'],
    landmarks: ['Cyberjaya D-Hub', 'Shaftsbury Square', 'Tamarind Square', 'MMU Campus', 'Putrajaya nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 55, max: 140 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Putrajaya',
    distanceToHub: '10 minutes',
    coordinates: { lat: '2.9213', lng: '101.6559' }
  },
  'putrajaya': {
    slug: 'putrajaya',
    population: 110000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'urban',
    petRisks: ['government area restrictions', 'man-made lake hazards', 'hot pavement burns', 'limited pet-friendly areas'],
    landmarks: ['Putrajaya Lake', 'IOI City Mall', 'Alamanda', 'Precinct 15', 'Pink Mosque'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 250, max: 600 },
    avgConsultationCost: { min: 70, max: 165 },
    avgGroomingCost: { min: 55, max: 135 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 5,
    coordinates: { lat: '2.9264', lng: '101.6964' }
  },

  // ========== KLANG HUB ==========
  'klang': {
    slug: 'klang',
    population: 878000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['port industrial toxins', 'flooding during monsoon', 'seafood allergies', 'stray dog packs'],
    landmarks: ['AEON Bukit Tinggi', 'Klang Parade', 'Istana Alam Shah', 'Little India Klang'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 400 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    coordinates: { lat: '3.0449', lng: '101.4455' }
  },
  'bandar-bukit-tinggi': {
    slug: 'bandar-bukit-tinggi',
    population: 125000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['shopping mall crowds', 'new township strays', 'pool drowning'],
    landmarks: ['AEON Bukit Tinggi', 'Bukit Tinggi Commercial', 'Klang Sentral nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 120 },
    avgGroomingCost: { min: 40, max: 95 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Klang',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.0031', lng: '101.4683' }
  },
  'kota-kemuning': {
    slug: 'kota-kemuning',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['gated community escapes', 'lake hazards', 'new development toxins'],
    landmarks: ['Gamuda Walk', 'Kota Kemuning Greenway', 'KK Lake', 'Rimbayu nearby'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 250, max: 600 },
    avgConsultationCost: { min: 70, max: 160 },
    avgGroomingCost: { min: 55, max: 140 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Klang',
    distanceToHub: '15 minutes',
    coordinates: { lat: '2.9908', lng: '101.5298' }
  },
  'meru': {
    slug: 'meru',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['industrial area strays', 'limited vet access', 'rural wildlife'],
    landmarks: ['Meru Raya', 'Tesco Meru', 'Meru Golf Club', 'Klang Port nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 350 },
    avgConsultationCost: { min: 35, max: 85 },
    avgGroomingCost: { min: 25, max: 65 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Klang',
    distanceToHub: '10 minutes',
    coordinates: { lat: '3.0847', lng: '101.4368' }
  },
  'port-klang': {
    slug: 'port-klang',
    population: 85000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['shipping container strays', 'seafood poisoning', 'flooding', 'port chemicals'],
    landmarks: ['Port Klang Ferry Terminal', 'Pelabuhan Klang', 'Pulau Ketam ferry', 'Port View'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 320 },
    avgConsultationCost: { min: 35, max: 80 },
    avgGroomingCost: { min: 25, max: 60 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Klang',
    distanceToHub: '20 minutes',
    coordinates: { lat: '3.0016', lng: '101.3930' }
  },
  
  // ========== JOHOR BAHRU HUB ==========
  'johor-bahru': {
    slug: 'johor-bahru',
    population: 858118,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['border crossing stress', 'high traffic density', 'seafood allergies', 'monsoon flooding', 'smuggling concerns'],
    landmarks: ['City Square', 'KSL City', 'Danga Bay', 'JB Sentral', 'Komtar JBCC'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    coordinates: { lat: '1.4927', lng: '103.7414' }
  },
  'tampoi': {
    slug: 'tampoi',
    population: 125000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['highway traffic', 'industrial strays', 'drainage hazards'],
    landmarks: ['AEON Tebrau City', 'Tampoi Industrial', 'Taman Pelangi nearby', 'CIQ nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 400 },
    avgConsultationCost: { min: 45, max: 110 },
    avgGroomingCost: { min: 35, max: 85 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Johor Bahru',
    distanceToHub: '15 minutes',
    coordinates: { lat: '1.5143', lng: '103.7162' }
  },
  'skudai': {
    slug: 'skudai',
    population: 245000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['university area strays', 'busy roads', 'new development hazards'],
    landmarks: ['UTM Campus', 'Skudai Parade', 'Sutera Mall', 'Taman Universiti'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Johor Bahru',
    distanceToHub: '20 minutes',
    coordinates: { lat: '1.5353', lng: '103.6582' }
  },
  'permas-jaya': {
    slug: 'permas-jaya',
    population: 89000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['coastal flooding', 'seafood waste', 'waterfront hazards'],
    landmarks: ['AEON Permas Jaya', 'Permas City', 'Permas Jaya Waterfront', 'Masai nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Johor Bahru',
    distanceToHub: '20 minutes',
    coordinates: { lat: '1.4686', lng: '103.9064' }
  },
  'taman-molek': {
    slug: 'taman-molek',
    population: 65000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['residential estate strays', 'park injuries', 'traffic accidents'],
    landmarks: ['Molek Pine Tower', 'Taman Molek Wet Market', 'Tebrau City nearby', 'Johor Jaya nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 170, max: 430 },
    avgConsultationCost: { min: 50, max: 120 },
    avgGroomingCost: { min: 40, max: 95 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Johor Bahru',
    distanceToHub: '15 minutes',
    coordinates: { lat: '1.5402', lng: '103.7856' }
  },
  
  // ========== KULAI HUB ==========
  'kulai': {
    slug: 'kulai',
    population: 240000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['Senai airport noise stress', 'palm oil plantation chemicals', 'highway traffic', 'semi-rural wildlife'],
    landmarks: ['IOI Mall Kulai', 'Senai International Airport', 'Taman Kempas', 'Kulai Jaya', 'North-South Highway'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Johor Bahru',
    distanceToHub: '25 minutes',
    coordinates: { lat: '1.6617', lng: '103.6019' }
  },
  'senai': {
    slug: 'senai',
    population: 85000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['airport cargo strays', 'industrial zone toxins', 'limited evening care', 'highway proximity'],
    landmarks: ['Senai Airport', 'Senai Industrial Park', 'Taman Scientex', 'Senai Hi-Tech Park'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 35, max: 88 },
    avgGroomingCost: { min: 25, max: 65 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Kulai',
    distanceToHub: '10 minutes',
    coordinates: { lat: '1.6342', lng: '103.6642' }
  },
  'taman-kempas': {
    slug: 'taman-kempas',
    population: 55000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['palm plantation proximity', 'estate dogs', 'limited vet options', 'rural pest exposure'],
    landmarks: ['Kempas Toll', 'Taman Kempas Utama', 'Kulai town nearby', 'IOI Mall nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 320 },
    avgConsultationCost: { min: 32, max: 82 },
    avgGroomingCost: { min: 22, max: 58 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kulai',
    distanceToHub: '8 minutes',
    coordinates: { lat: '1.6389', lng: '103.5987' }
  },

  // ========== ISKANDAR HUB ==========
  'iskandar-puteri': {
    slug: 'iskandar-puteri',
    population: 529074,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['new development strays', 'theme park escapees', 'waterfront hazards', 'construction sites'],
    landmarks: ['LEGOLAND', 'Puteri Harbour', 'EduCity', 'Medini', 'Mall of Medini'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 280, max: 700 },
    avgConsultationCost: { min: 80, max: 180 },
    avgGroomingCost: { min: 60, max: 150 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 1,
    coordinates: { lat: '1.4294', lng: '103.6278' }
  },
  'gelang-patah': {
    slug: 'gelang-patah',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['border proximity stress', 'industrial areas', 'rural wildlife'],
    landmarks: ['Second Link', 'Tanjung Kupang', 'Gelang Patah town', 'Tuas nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 95 },
    avgGroomingCost: { min: 30, max: 75 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Iskandar Puteri',
    distanceToHub: '15 minutes',
    coordinates: { lat: '1.4017', lng: '103.5884' }
  },
  'nusajaya': {
    slug: 'nusajaya',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['new township hazards', 'limited vet access initially', 'waterfront dangers'],
    landmarks: ['Kota Iskandar', 'Afiat Healthpark', 'Nusajaya Square', 'Horizon Hills'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Iskandar Puteri',
    distanceToHub: '10 minutes',
    coordinates: { lat: '1.4539', lng: '103.6347' }
  },
  'bukit-indah': {
    slug: 'bukit-indah',
    population: 145000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['shopping traffic', 'gated community issues', 'playground injuries'],
    landmarks: ['AEON Bukit Indah', 'Bukit Indah Walk', 'Taman Bukit Indah', 'Austin Heights nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 190, max: 480 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 45, max: 105 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Iskandar Puteri',
    distanceToHub: '15 minutes',
    coordinates: { lat: '1.4842', lng: '103.6623' }
  },
  
  // ========== PENANG HUB ==========
  'george-town': {
    slug: 'george-town',
    population: 708127,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['heritage building hazards', 'tourist area crowds', 'seafood allergies', 'narrow street traffic'],
    landmarks: ['Komtar', 'Gurney Plaza', 'Straits Quay', 'Penang Road', 'Armenian Street'],
    vetPriceTier: 'premium',
    avgEmergencyVetCost: { min: 280, max: 700 },
    avgConsultationCost: { min: 80, max: 180 },
    avgGroomingCost: { min: 60, max: 150 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    coordinates: { lat: '5.4141', lng: '100.3288' }
  },
  'tanjung-tokong': {
    slug: 'tanjung-tokong',
    population: 67000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['beach hazards', 'tourist crowds', 'seafood waste', 'coastal erosion'],
    landmarks: ['Island Plaza', 'Tanjung Tokong Market', 'Floating Mosque', 'Tanjung Bungah nearby'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 50, max: 120 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 3,
    nearestMajorCity: 'George Town',
    distanceToHub: '10 minutes',
    coordinates: { lat: '5.4566', lng: '100.3045' }
  },
  'tanjung-bungah': {
    slug: 'tanjung-bungah',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['beach drowning', 'jellyfish stings', 'landslide areas', 'tourist traffic'],
    landmarks: ['Miami Beach', 'Tanjung Bungah Beach', 'ESCAPE Penang nearby', 'Tropical Spice Garden'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 200, max: 500 },
    avgConsultationCost: { min: 60, max: 140 },
    avgGroomingCost: { min: 50, max: 120 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    nearestMajorCity: 'George Town',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.4705', lng: '100.2907' }
  },
  'gelugor': {
    slug: 'gelugor',
    population: 112000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['university traffic', 'hospital area strays', 'industrial nearby'],
    landmarks: ['USM Campus', 'Penang General Hospital', 'Gelugor Market', 'Sungai Nibong'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 5,
    nearestMajorCity: 'George Town',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.3588', lng: '100.3056' }
  },
  'bayan-lepas': {
    slug: 'bayan-lepas',
    population: 156000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['airport noise stress', 'industrial chemicals', 'highway traffic', 'free trade zone hazards'],
    landmarks: ['Queensbay Mall', 'Penang Airport', 'FTZ Bayan Lepas', 'Bayan Point'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 55, max: 130 },
    avgGroomingCost: { min: 45, max: 110 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 0,
    nearestMajorCity: 'George Town',
    distanceToHub: '20 minutes',
    coordinates: { lat: '5.3032', lng: '100.2723' }
  },
  'air-itam': {
    slug: 'air-itam',
    population: 89000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'highland',
    petRisks: ['hill temple crowds', 'steep terrain', 'monkey encounters', 'foggy road accidents'],
    landmarks: ['Kek Lok Si Temple', 'Penang Hill', 'Air Itam Dam', 'Air Itam Market'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 45, max: 110 },
    avgGroomingCost: { min: 35, max: 90 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 1,
    nearestMajorCity: 'George Town',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.4019', lng: '100.2750' }
  },
  
  // ========== SEBERANG PERAI HUB ==========
  'butterworth': {
    slug: 'butterworth',
    population: 137000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['ferry terminal crowds', 'railway hazards', 'industrial pollution', 'port traffic'],
    landmarks: ['Penang Sentral', 'Butterworth Ferry Terminal', 'Sunway Carnival Mall', 'Raja Uda'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    coordinates: { lat: '5.3991', lng: '100.3638' }
  },
  'bukit-mertajam': {
    slug: 'bukit-mertajam',
    population: 245000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['market strays', 'temple crowds', 'old town traffic', 'monsoon flooding'],
    landmarks: ['BM Plaza', 'Cherok Tokun', 'Bukit Mertajam Market', 'BM Parade'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 35, max: 90 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Butterworth',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.3633', lng: '100.4617' }
  },
  'perai': {
    slug: 'perai',
    population: 112000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['industrial area chemicals', 'heavy vehicle traffic', 'factory strays', 'flooding'],
    landmarks: ['Perai Industrial Zone', 'Auto City', 'Mydin Penang', 'PLUS Highway'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 320 },
    avgConsultationCost: { min: 35, max: 85 },
    avgGroomingCost: { min: 25, max: 65 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Butterworth',
    distanceToHub: '10 minutes',
    coordinates: { lat: '5.3847', lng: '100.3991' }
  },
  'kepala-batas': {
    slug: 'kepala-batas',
    population: 65000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['rural wildlife', 'agricultural chemicals', 'limited vet access', 'snake encounters'],
    landmarks: ['Kepala Batas Town', 'Tasek Gelugor nearby', 'Agricultural areas', 'Bertam'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 100, max: 280 },
    avgConsultationCost: { min: 30, max: 75 },
    avgGroomingCost: { min: 20, max: 55 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Butterworth',
    distanceToHub: '25 minutes',
    coordinates: { lat: '5.5170', lng: '100.4321' }
  },
  'nibong-tebal': {
    slug: 'nibong-tebal',
    population: 45000,
    populationTier: 'small',
    areaType: 'rural',
    climate: 'inland',
    petRisks: ['farming chemicals', 'rural strays', 'limited emergency care', 'wildlife encounters'],
    landmarks: ['UiTM Nibong Tebal', 'Nibong Tebal Town', 'Jawi nearby', 'Valdor'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 100, max: 260 },
    avgConsultationCost: { min: 28, max: 70 },
    avgGroomingCost: { min: 20, max: 50 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Butterworth',
    distanceToHub: '30 minutes',
    coordinates: { lat: '5.1646', lng: '100.4751' }
  },
  
  // ========== IPOH HUB ==========
  'ipoh': {
    slug: 'ipoh',
    population: 759952,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['limestone cave hazards', 'old town traffic', 'tourist area crowds', 'tin mining legacy toxins'],
    landmarks: ['Ipoh Old Town', 'Kinta City', 'AEON Ipoh', 'Ipoh Parade', 'Concubine Lane'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 160, max: 420 },
    avgConsultationCost: { min: 45, max: 110 },
    avgGroomingCost: { min: 35, max: 90 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 3,
    coordinates: { lat: '4.5975', lng: '101.0901' }
  },
  'menglembu': {
    slug: 'menglembu',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['old mining areas', 'rural transition hazards', 'limited vet hours'],
    landmarks: ['Menglembu Market', 'Tin mining heritage', 'Near Jelapang', 'Lahat'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 320 },
    avgConsultationCost: { min: 35, max: 85 },
    avgGroomingCost: { min: 25, max: 65 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Ipoh',
    distanceToHub: '15 minutes',
    coordinates: { lat: '4.6389', lng: '101.0628' }
  },
  'tambun': {
    slug: 'tambun',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['hot springs chemicals', 'theme park strays', 'limestone cave animals'],
    landmarks: ['Lost World of Tambun', 'Tambun Hot Springs', 'Sunway City Ipoh', 'Kinta Valley'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 150, max: 380 },
    avgConsultationCost: { min: 45, max: 105 },
    avgGroomingCost: { min: 35, max: 85 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Ipoh',
    distanceToHub: '20 minutes',
    coordinates: { lat: '4.6133', lng: '101.1397' }
  },
  'bercham': {
    slug: 'bercham',
    population: 56000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['residential estate strays', 'market waste', 'old housing hazards'],
    landmarks: ['Bercham Market', 'Taman Bercham', 'Ipoh Spectra', 'Near Gunung Rapat'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 300 },
    avgConsultationCost: { min: 35, max: 80 },
    avgGroomingCost: { min: 25, max: 60 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Ipoh',
    distanceToHub: '10 minutes',
    coordinates: { lat: '4.6336', lng: '101.1003' }
  },
  'simpang-pulai': {
    slug: 'simpang-pulai',
    population: 32000,
    populationTier: 'small',
    areaType: 'rural',
    climate: 'highland',
    petRisks: ['mountain road accidents', 'cold exposure', 'limited vet access', 'wildlife'],
    landmarks: ['Cameron Highlands turn-off', 'Simpang Pulai bypass', 'Gunung Rapat', 'Limestone hills'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 100, max: 280 },
    avgConsultationCost: { min: 30, max: 75 },
    avgGroomingCost: { min: 22, max: 55 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Ipoh',
    distanceToHub: '20 minutes',
    coordinates: { lat: '4.5189', lng: '101.1431' }
  },
  
  // ========== KUCHING HUB ==========
  'kuching': {
    slug: 'kuching',
    population: 570407,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['Sarawak River flooding', 'wildlife from nearby forests', 'high humidity skin issues', 'cat monument tourists'],
    landmarks: ['Kuching Waterfront', 'Cat Museum', 'The Spring Mall', 'Vivacity Megamall', 'Padungan'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 4,
    coordinates: { lat: '1.5535', lng: '110.3593' }
  },
  'petra-jaya': {
    slug: 'petra-jaya',
    population: 89000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['government area security', 'bridge traffic', 'waterfront hazards'],
    landmarks: ['Sarawak State Assembly', 'Petra Jaya Complex', 'ICOM', 'DUN Complex'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Kuching',
    distanceToHub: '10 minutes',
    coordinates: { lat: '1.5661', lng: '110.3449' }
  },
  'kota-samarahan': {
    slug: 'kota-samarahan',
    population: 145000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['university strays', 'new development hazards', 'rural transition areas'],
    landmarks: ['UNIMAS', 'Samarahan Town', 'Summer Mall', 'Desa Ilmu'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Kuching',
    distanceToHub: '25 minutes',
    coordinates: { lat: '1.4689', lng: '110.4277' }
  },
  'pending': {
    slug: 'pending',
    population: 67000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['industrial area chemicals', 'heavy traffic', 'factory strays'],
    landmarks: ['Pending Industrial', 'CKS Shopping Centre', 'Demak Laut', 'Airport nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Kuching',
    distanceToHub: '15 minutes',
    coordinates: { lat: '1.5250', lng: '110.4031' }
  },
  'batu-kawa': {
    slug: 'batu-kawa',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['new township strays', 'construction sites', 'limited senior vet care'],
    landmarks: ['Batu Kawa New Township', 'Satok Sunday Market nearby', 'BJC Mall', 'Matang'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kuching',
    distanceToHub: '20 minutes',
    coordinates: { lat: '1.5444', lng: '110.2947' }
  },
  
  // ========== KOTA KINABALU HUB ==========
  'kota-kinabalu': {
    slug: 'kota-kinabalu',
    population: 500421,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['island hopping dangers', 'mountain altitude sickness', 'tropical storms', 'diverse wildlife encounters'],
    landmarks: ['Suria Sabah', 'Jesselton Point', 'Signal Hill', 'Imago Mall', 'KK Waterfront'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 180, max: 450 },
    avgConsultationCost: { min: 50, max: 130 },
    avgGroomingCost: { min: 40, max: 100 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 5,
    coordinates: { lat: '5.9804', lng: '116.0735' }
  },
  'likas': {
    slug: 'likas',
    population: 78000,
    populationTier: 'small',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['mangrove wildlife', 'bird sanctuary hazards', 'waterfront strays'],
    landmarks: ['Likas Bay', 'City Mosque', 'Likas Sports Complex', 'Queen Elizabeth Hospital'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 170, max: 430 },
    avgConsultationCost: { min: 48, max: 120 },
    avgGroomingCost: { min: 38, max: 95 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Kota Kinabalu',
    distanceToHub: '10 minutes',
    coordinates: { lat: '5.9627', lng: '116.0949' }
  },
  'inanam': {
    slug: 'inanam',
    population: 67000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['rural-urban transition strays', 'new development hazards', 'wildlife from Crocker Range'],
    landmarks: ['Inanam Laut', 'Bundusan', 'Near Crocker Range', 'Menggatal nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 1,
    nearestMajorCity: 'Kota Kinabalu',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.9961', lng: '116.1294' }
  },
  'penampang': {
    slug: 'penampang',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['cultural festival crowds', 'rural wildlife', 'agricultural chemicals'],
    landmarks: ['Donggongon', 'Hongkod Koisaan', 'Penampang Town', 'Kadazan cultural village'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kota Kinabalu',
    distanceToHub: '15 minutes',
    coordinates: { lat: '5.9206', lng: '116.1150' }
  },
  'putatan': {
    slug: 'putatan',
    population: 89000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['coastal flooding', 'fishing village strays', 'limited vet hours'],
    landmarks: ['Putatan Wetlands', '1Borneo nearby', 'Putatan Beach', 'Lok Kawi Wildlife Park nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 1,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kota Kinabalu',
    distanceToHub: '20 minutes',
    coordinates: { lat: '5.9139', lng: '116.0552' }
  },
  
  // ========== MELAKA HUB ==========
  'melaka-city': {
    slug: 'melaka-city',
    population: 579000,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['heritage area crowds', 'tourist feeding dangers', 'river boat hazards', 'Jonker Street traffic'],
    landmarks: ['Jonker Street', 'A Famosa', 'Mahkota Parade', 'Dataran Pahlawan', 'Melaka River'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 160, max: 420 },
    avgConsultationCost: { min: 48, max: 120 },
    avgGroomingCost: { min: 38, max: 95 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 1,
    coordinates: { lat: '2.1896', lng: '102.2501' }
  },
  'ayer-keroh': {
    slug: 'ayer-keroh',
    population: 98000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['zoo/theme park visitors', 'highway traffic', 'recreational lake hazards'],
    landmarks: ['AEON Ayer Keroh', 'Zoo Melaka', 'Mini Malaysia', 'Melaka Botanical Garden'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 160, max: 400 },
    avgConsultationCost: { min: 45, max: 115 },
    avgGroomingCost: { min: 35, max: 90 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Melaka City',
    distanceToHub: '15 minutes',
    coordinates: { lat: '2.2678', lng: '102.2892' }
  },
  'klebang': {
    slug: 'klebang',
    population: 67000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['beach hazards', 'seafood allergies', 'tourist crowds at beach'],
    landmarks: ['Klebang Beach', 'Klebang Original Coconut Shake', 'Tanjung Kling nearby', 'Pantai Puteri'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 140, max: 360 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Melaka City',
    distanceToHub: '10 minutes',
    coordinates: { lat: '2.2281', lng: '102.1658' }
  },
  'bukit-beruang': {
    slug: 'bukit-beruang',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['university strays', 'hilly terrain hazards', 'new development areas'],
    landmarks: ['Multimedia University', 'Bukit Beruang area', 'UTeM nearby', 'Educational hub'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 2,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Melaka City',
    distanceToHub: '20 minutes',
    coordinates: { lat: '2.2503', lng: '102.3128' }
  },
  
  // ========== ALOR SETAR HUB ==========
  'alor-setar': {
    slug: 'alor-setar',
    population: 405523,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['paddy field chemicals', 'monsoon flooding', 'Thai border traffic', 'rural wildlife'],
    landmarks: ['Aman Central', 'Alor Setar Tower', 'Pekan Rabu', 'Zahir Mosque', 'Paddy Museum'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 2,
    coordinates: { lat: '6.1248', lng: '100.3682' }
  },
  'jitra': {
    slug: 'jitra',
    population: 89000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['agricultural chemicals', 'rural strays', 'limited 24h care', 'monsoon dangers'],
    landmarks: ['Jitra Town', 'Chuping', 'Changlun nearby', 'Near Thai border'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 100, max: 280 },
    avgConsultationCost: { min: 30, max: 75 },
    avgGroomingCost: { min: 20, max: 55 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Alor Setar',
    distanceToHub: '20 minutes',
    coordinates: { lat: '6.2656', lng: '100.4211' }
  },
  'sungai-petani': {
    slug: 'sungai-petani',
    population: 443488,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['industrial strays', 'highway traffic', 'monsoon flooding', 'rapid development hazards'],
    landmarks: ['Central Square', 'SP Plaza', 'Cinta Sayang Golf', 'Bujang Valley'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 4,
    nearestMajorCity: 'Alor Setar',
    distanceToHub: '45 minutes',
    coordinates: { lat: '5.6474', lng: '100.4880' }
  },
  'kulim': {
    slug: 'kulim',
    population: 298000,
    populationTier: 'medium',
    areaType: 'urban',
    climate: 'inland',
    petRisks: ['hi-tech park chemicals', 'industrial traffic', 'new development strays'],
    landmarks: ['Kulim Hi-Tech Park', 'Kulim Town', 'Kulim Central', 'Near Penang border'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 3,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Alor Setar',
    distanceToHub: '60 minutes',
    coordinates: { lat: '5.3650', lng: '100.5610' }
  },
  
  // ========== KUANTAN HUB ==========
  'kuantan': {
    slug: 'kuantan',
    population: 607778,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['monsoon flooding', 'beach hazards', 'jellyfish stings', 'port industrial areas'],
    landmarks: ['East Coast Mall', 'Kuantan Waterfront', 'Teluk Cempedak', 'Sungai Lembing'],
    vetPriceTier: 'standard',
    avgEmergencyVetCost: { min: 160, max: 420 },
    avgConsultationCost: { min: 45, max: 115 },
    avgGroomingCost: { min: 35, max: 90 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 1,
    coordinates: { lat: '3.8126', lng: '103.3256' }
  },
  'indera-mahkota': {
    slug: 'indera-mahkota',
    population: 156000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['university strays', 'new township hazards', 'limited evening care'],
    landmarks: ['UMP Campus', 'Indera Mahkota Town', 'East Coast Mall nearby', 'Mega Mall'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    nearestMajorCity: 'Kuantan',
    distanceToHub: '15 minutes',
    coordinates: { lat: '3.8356', lng: '103.2789' }
  },
  'gebeng': {
    slug: 'gebeng',
    population: 45000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['petrochemical industry', 'industrial area strays', 'limited vet access', 'port traffic'],
    landmarks: ['Gebeng Industrial Estate', 'Petronas Petrochemicals', 'Kuantan Port nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 300 },
    avgConsultationCost: { min: 35, max: 85 },
    avgGroomingCost: { min: 25, max: 60 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kuantan',
    distanceToHub: '25 minutes',
    coordinates: { lat: '3.9417', lng: '103.4128' }
  },
  
  // ========== KOTA BHARU HUB ==========
  'kota-bharu': {
    slug: 'kota-bharu',
    population: 491237,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['severe monsoon flooding', 'Thai border traffic', 'conservative area pet restrictions', 'beach hazards'],
    landmarks: ['KB Mall', 'Siti Khadijah Market', 'Istana Balai Besar', 'Pantai Cahaya Bulan'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 120, max: 320 },
    avgConsultationCost: { min: 35, max: 90 },
    avgGroomingCost: { min: 25, max: 65 },
    testimonialPoolIndex: 4,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 4,
    coordinates: { lat: '6.1254', lng: '102.2381' }
  },
  'kubang-kerian': {
    slug: 'kubang-kerian',
    population: 145000,
    populationTier: 'medium',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['hospital area strays', 'university crowds', 'monsoon flooding'],
    landmarks: ['Hospital USM', 'USM Health Campus', 'Kubang Kerian Town', 'HUSM'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 110, max: 290 },
    avgConsultationCost: { min: 32, max: 80 },
    avgGroomingCost: { min: 22, max: 58 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 5,
    nearestMajorCity: 'Kota Bharu',
    distanceToHub: '10 minutes',
    coordinates: { lat: '6.1197', lng: '102.2894' }
  },
  'pengkalan-chepa': {
    slug: 'pengkalan-chepa',
    population: 89000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['airport noise stress', 'flooding', 'rural transition strays'],
    landmarks: ['Sultan Ismail Petra Airport', 'Pengkalan Chepa Town', 'UMK nearby'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 100, max: 270 },
    avgConsultationCost: { min: 30, max: 75 },
    avgGroomingCost: { min: 20, max: 55 },
    testimonialPoolIndex: 1,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    nearestMajorCity: 'Kota Bharu',
    distanceToHub: '15 minutes',
    coordinates: { lat: '6.1692', lng: '102.2928' }
  },
  
  // ========== KUALA TERENGGANU HUB ==========
  'kuala-terengganu': {
    slug: 'kuala-terengganu',
    population: 337553,
    populationTier: 'major',
    areaType: 'urban',
    climate: 'coastal',
    petRisks: ['severe monsoon flooding', 'fishing village strays', 'beach hazards', 'turtle conservation areas'],
    landmarks: ['Pasar Payang', 'Crystal Mosque', 'Chinatown', 'Pantai Batu Buruk', 'Drawbridge'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 130, max: 340 },
    avgConsultationCost: { min: 38, max: 95 },
    avgGroomingCost: { min: 28, max: 70 },
    testimonialPoolIndex: 2,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 2,
    coordinates: { lat: '5.3117', lng: '103.1324' }
  },
  'gong-badak': {
    slug: 'gong-badak',
    population: 78000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'coastal',
    petRisks: ['university strays', 'coastal flooding', 'beach hazards'],
    landmarks: ['UMT Campus', 'Gong Badak Beach', 'Mesra Mall nearby', 'Pantai Batu Rakit'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 110, max: 290 },
    avgConsultationCost: { min: 32, max: 82 },
    avgGroomingCost: { min: 22, max: 58 },
    testimonialPoolIndex: 3,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 3,
    nearestMajorCity: 'Kuala Terengganu',
    distanceToHub: '20 minutes',
    coordinates: { lat: '5.3892', lng: '103.0872' }
  }
};

// Helper function to get city metadata with fallback
export const getCityMetadata = (citySlug: string): CityMetadata => {
  const metadata = cityMetadata[citySlug];
  if (metadata) return metadata;
  
  // Return default metadata for cities not explicitly defined
  return {
    slug: citySlug,
    population: 50000,
    populationTier: 'small',
    areaType: 'suburban',
    climate: 'inland',
    petRisks: ['traffic accidents', 'stray animal encounters', 'heat exposure'],
    landmarks: ['Town Centre', 'Local Market', 'Main Road'],
    vetPriceTier: 'budget',
    avgEmergencyVetCost: { min: 150, max: 400 },
    avgConsultationCost: { min: 40, max: 100 },
    avgGroomingCost: { min: 30, max: 80 },
    testimonialPoolIndex: 0,
    scenarioPoolIndex: 0,
    vetAdviceIndex: 0,
    coordinates: { lat: '3.1390', lng: '101.6869' }
  };
};

// Get DVS office for a state
export const getDVSOffice = (state: string): DVSOffice => {
  return dvsOffices[state] || dvsOffices['W.P. Kuala Lumpur'];
};

// Get local council for a city (with fallback to state-level)
export const getLocalCouncil = (citySlug: string, state: string): LocalCouncil => {
  const council = localCouncils[citySlug];
  if (council) return council;
  
  // Fallback councils by state
  const stateFallbacks: Record<string, LocalCouncil> = {
    'W.P. Kuala Lumpur': localCouncils['kuala-lumpur'],
    'Selangor': localCouncils['petaling-jaya'],
    'Johor': localCouncils['johor-bahru'],
    'Penang': localCouncils['george-town'],
    'Perak': localCouncils['ipoh'],
    'Sarawak': localCouncils['kuching'],
    'Sabah': localCouncils['kota-kinabalu'],
    'Melaka': localCouncils['melaka-city'],
    'Kedah': localCouncils['alor-setar'],
    'Pahang': localCouncils['kuantan'],
    'Kelantan': localCouncils['kota-bharu'],
    'Terengganu': localCouncils['kuala-terengganu']
  };
  
  return stateFallbacks[state] || {
    name: 'Local Council',
    shortName: 'Council',
    website: 'https://www.malaysia.gov.my',
    dogLicenseFee: 'RM20/year',
    spayedFee: 'RM10/year'
  };
};
