project_id = "xdincsheohvgxewpfwlg"

[functions.sitemap]
verify_jwt = false

[functions.ask-pet-question]
verify_jwt = false

[functions.get-state-qa-list]
verify_jwt = false

[functions.get-qa-answer]
verify_jwt = false
